# contains global variables for file locations

GLOBAL_PROJECT_DIR = "CHANGE THIS TEXT TO YOUR WORKING DIRECTORY"

GLOBAL_NCORES = 3

GLOBAL_DATA_DIR = paste0(GLOBAL_PROJECT_DIR, "data/")
GLOBAL_CHR_MTX_DIR = paste0(GLOBAL_DATA_DIR, "individual_chromosome_matrices/")

GLOBAL_OUT_DIR = paste0(GLOBAL_PROJECT_DIR, "out/")
GLOBAL_PANEL_DIR = paste0(GLOBAL_OUT_DIR, "SIGNATURE_PANELS/")
GLOBAL_PANEL_SBS_DIR = paste0(GLOBAL_PANEL_DIR, "SBS_MATRICES/")

GLOBAL_BASELINE_PANEL_DIR = paste0(GLOBAL_DATA_DIR, "BASELINE_PANELS/")
GLOBAL_BASELINE_SIG_EST_DIR = paste0(GLOBAL_DATA_DIR, "BASELINE_PANELS/SIGNATURE_ESTIMATES/")
GLOBAL_BASELINE_SBS_DIR = paste0(GLOBAL_DATA_DIR, "BASELINE_PANELS/SBS_MATRICES/")

GLOBAL_LOGFILE_DIR = paste0(GLOBAL_OUT_DIR, "LOG_FILES/")
GLOBAL_PANEL_SIG_EST_DIR = paste0(GLOBAL_PANEL_DIR, "SIGNATURE_ESTIMATES/")


GLOBAL_SCRIPT_OUT = paste0(GLOBAL_OUT_DIR, "SCRIPT_OUTS/")
GLOBAL_SCRIPT_LOG_DIR = paste0(GLOBAL_SCRIPT_OUT, "LOG_FILES/")
GLOBAL_SCRIPT_PANEL_SBS_DIR = paste0(GLOBAL_SCRIPT_OUT, "PANEL_SBS_MATRICES/")
GLOBAL_SCRIPT_PANEL_WINDOWS_DIR = paste0(GLOBAL_SCRIPT_OUT, "PANEL_WINDOWS/")
GLOBAL_SCRIPT_PANEL_SIG_EST_DIR = paste0(GLOBAL_SCRIPT_OUT, "PANEL_SIGNATURE_ESTIMATES/") 
GLOBAL_SCRIPT_TEST_TRAIN_DIR = paste0(GLOBAL_SCRIPT_OUT, "TEST_TRAIN_SETS/")

GLOBAL_SCRIPT_BASELINE_WINDOWS = paste0(GLOBAL_SCRIPT_OUT, "BASELINE_WINDOWS/")
GLOBAL_SCRIPT_BASELINE_SBS = paste0(GLOBAL_SCRIPT_OUT, "BASELINE_SBS/") 
GLOBAL_SCRIPT_SIG_EST = paste0(GLOBAL_SCRIPT_OUT, "BASELINE_SIG_EST/")   


GLOBAL_SIZE_TEST_WINDOWS_DIR = paste0(GLOBAL_SCRIPT_PANEL_WINDOWS_DIR, "SIZE_TEST_PW/")
GLOBAL_SIZE_TEST_SBS_DIR = paste0(GLOBAL_SCRIPT_PANEL_SBS_DIR, "SIZE_TEST_SBS/")
GLOBAL_SIZE_TEST_SIG_EST_DIR = paste0(GLOBAL_SCRIPT_PANEL_SIG_EST_DIR, "SIZE_TEST_SE/")


GLOBAL_GENERAL_PANEL_DIR = paste0(GLOBAL_SCRIPT_OUT, "GENERAL_PANEL_DIRS/")

GLOBAL_GP_TEST_TRAIN_DIR = paste0(GLOBAL_GENERAL_PANEL_DIR, "GP_TEST_TRAIN_SETS/")
GLOBAL_GP_WINDOWS_DIR = paste0(GLOBAL_GENERAL_PANEL_DIR, "GP_WINDOWS/")
GLOBAL_GP_IND_WIN_DIR = paste0(GLOBAL_GENERAL_PANEL_DIR, "INDIVIDUAL_SIG_WINDOWS/")
GLOBAL_GP_SBS_DIR = paste0(GLOBAL_GENERAL_PANEL_DIR, "GP_SBS_MATRICES/")
GLOBAL_GP_SIG_EST_DIR = paste0(GLOBAL_GENERAL_PANEL_DIR, "GP_SIGNATURE_ESTIMATES/")

